---
title: "Yelp Milestone Report Rubric"
output:
  pdf_document:
    highlight: haddock
  html_document: default
  word_document: default
---

Below we give the rubric for the milestone report to help you prepare your submission:

#	Prompt:
Now is the point where you want to identify a question or a problem that you are interested in addressing with the data for this capstone project. Write down that question in just 1 to 3 sentences so that another person who is as familiar with the dataset as you are would be able to understand and assess it. The goal of this peer assessment is to obtain some feedback from your peers regarding various aspects of your question or problem and to help you make adjustments as necessary. 

#	Question
Write down in 1 to 3 sentences the question or problem that you intend to address for this capstone project.

#	Evaluation criterion
Is this question of interest to you? 

NOTE: Do not address the issue of answerability in your response, merely state whether you find it an interesting question or not.

#	Evaluation criterion
What audience(s) might be interested in having this question / problem addressed?


#	Evaluation criterion
Is the question answerable from the the Yelp dataset, or some combination of the Yelp dataset and another (external) dataset?

0 points: The question is not answerable using the Yelp dataset or some combination of the Yelp dataset and another dataset
2 points: The question is likely answerable using the dataset 
4 points: The question is definitely answerable using the dataset

#	Evaluation criterion
How specific is the question being asked or the problem being posed?

0 points: The question / problem is so broad in scope that the answer will likely not be of interest or useful.
1 point: The question / problem is reasonably specific so that an answer will likely be interpretable or actionable.





